steps:
  - label: "Run build steps (small)"
    commands:
      - ./record-system-info.sh 
      - ./install-deps-debian.sh
      - ./download-kernel.sh
      - ./build-kernel.sh
    artifact_paths:
      - "compile_time_output.txt"
      - "system_info.txt"
    agents:
      queue: "linux-graphql-demo-extra-large"
  - label: "Run build steps (medium)"
    commands:
      - ./record-system-info.sh 
      - ./install-deps-debian.sh
      - ./download-kernel.sh
      - ./build-kernel.sh
    artifact_paths:
      - "compile_time_output.txt"
      - "system_info.txt"
    agents:
      queue: "hosted-medium"
  - label: "Run build steps (large)"
    commands:
      - ./record-system-info.sh 
      - ./install-deps-debian.sh
      - ./download-kernel.sh
      - ./build-kernel.sh
    artifact_paths:
      - "compile_time_output.txt"
      - "system_info.txt"
    agents:
      queue: "hosted-large"
